development:
  adapter: postgres
  database: core

test:
  adapter: sqlite
  database: test.db

test_mysql:
  adapter: mysql2
  encoding: utf8
  charset: utf8
  database: test_lims_core
  username: root
  password:
  socket: /tmp/mysql.sock
